---
pid: tmp/pids/thin.pid
address: 10.18.83.134
timeout: 30
wait: 30
port: 3000
log: log/thin.log
max_conns: 1024
require: []
Listen: 80
Listen: 443 https

environment: production
max_persistent_conns: 512
servers: 4
daemonize: true
chdir: /home/knome/sailesh/first_app/current